name: EDK2 build

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  edk2-build:
    runs-on: ubuntu-22.04
    steps:
    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends acpica-tools gcc-aarch64-linux-gnu

    - name: Check out code
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build RPI_EFI.fd
      run: make -j$(nproc) RPI_EFI.fd

    - name: Generate SHA256SUMS
      run: sha256sum RPI_EFI.fd > SHA256SUMS

    - name: Upload RPI_EFI.fd to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: RPI_EFI.fd

    - name: Upload SHA256SUMS to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: SHA256SUMS
